name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify
        run: make check

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
